name: DataOps Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: python scripts/run_all.py
